// Code generated by go-swagger; DO NOT EDIT.

package employees_utilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesFilterPresetsGetParams creates a new EmployeesFilterPresetsGetParams object
// with the default values initialized.
func NewEmployeesFilterPresetsGetParams() *EmployeesFilterPresetsGetParams {
	var ()
	return &EmployeesFilterPresetsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesFilterPresetsGetParamsWithTimeout creates a new EmployeesFilterPresetsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesFilterPresetsGetParamsWithTimeout(timeout time.Duration) *EmployeesFilterPresetsGetParams {
	var ()
	return &EmployeesFilterPresetsGetParams{

		timeout: timeout,
	}
}

// NewEmployeesFilterPresetsGetParamsWithContext creates a new EmployeesFilterPresetsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesFilterPresetsGetParamsWithContext(ctx context.Context) *EmployeesFilterPresetsGetParams {
	var ()
	return &EmployeesFilterPresetsGetParams{

		Context: ctx,
	}
}

// NewEmployeesFilterPresetsGetParamsWithHTTPClient creates a new EmployeesFilterPresetsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesFilterPresetsGetParamsWithHTTPClient(client *http.Client) *EmployeesFilterPresetsGetParams {
	var ()
	return &EmployeesFilterPresetsGetParams{
		HTTPClient: client,
	}
}

/*EmployeesFilterPresetsGetParams contains all the parameters to send to the API endpoint
for the employees filter presets get operation typically these are written to a http.Request
*/
type EmployeesFilterPresetsGetParams struct {

	/*DepartmentID*/
	DepartmentID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) WithTimeout(timeout time.Duration) *EmployeesFilterPresetsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) WithContext(ctx context.Context) *EmployeesFilterPresetsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) WithHTTPClient(client *http.Client) *EmployeesFilterPresetsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDepartmentID adds the departmentID to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) WithDepartmentID(departmentID *int64) *EmployeesFilterPresetsGetParams {
	o.SetDepartmentID(departmentID)
	return o
}

// SetDepartmentID adds the departmentId to the employees filter presets get params
func (o *EmployeesFilterPresetsGetParams) SetDepartmentID(departmentID *int64) {
	o.DepartmentID = departmentID
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesFilterPresetsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DepartmentID != nil {

		// query param department_id
		var qrDepartmentID int64
		if o.DepartmentID != nil {
			qrDepartmentID = *o.DepartmentID
		}
		qDepartmentID := swag.FormatInt64(qrDepartmentID)
		if qDepartmentID != "" {
			if err := r.SetQueryParam("department_id", qDepartmentID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
