// Code generated by go-swagger; DO NOT EDIT.

package employees_utilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new employees utilities API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for employees utilities API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
EmployeesContactsCountsGet gets the aggregates on how many employees have contact information set and which exactly
*/
func (a *Client) EmployeesContactsCountsGet(params *EmployeesContactsCountsGetParams, authInfo runtime.ClientAuthInfoWriter) (*EmployeesContactsCountsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEmployeesContactsCountsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "EmployeesContacts_countsGet",
		Method:             "GET",
		PathPattern:        "/employees/contacts_counts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &EmployeesContactsCountsGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*EmployeesContactsCountsGetOK), nil

}

/*
EmployeesFilterPresetsGet gets the list of predefined employee list filters
*/
func (a *Client) EmployeesFilterPresetsGet(params *EmployeesFilterPresetsGetParams, authInfo runtime.ClientAuthInfoWriter) (*EmployeesFilterPresetsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEmployeesFilterPresetsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "EmployeesFilter_presetsGet",
		Method:             "GET",
		PathPattern:        "/employees/filter_presets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &EmployeesFilterPresetsGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*EmployeesFilterPresetsGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
