// Code generated by go-swagger; DO NOT EDIT.

package device_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeviceRegistrationRegisterPostParams creates a new DeviceRegistrationRegisterPostParams object
// with the default values initialized.
func NewDeviceRegistrationRegisterPostParams() *DeviceRegistrationRegisterPostParams {
	var ()
	return &DeviceRegistrationRegisterPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceRegistrationRegisterPostParamsWithTimeout creates a new DeviceRegistrationRegisterPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceRegistrationRegisterPostParamsWithTimeout(timeout time.Duration) *DeviceRegistrationRegisterPostParams {
	var ()
	return &DeviceRegistrationRegisterPostParams{

		timeout: timeout,
	}
}

// NewDeviceRegistrationRegisterPostParamsWithContext creates a new DeviceRegistrationRegisterPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceRegistrationRegisterPostParamsWithContext(ctx context.Context) *DeviceRegistrationRegisterPostParams {
	var ()
	return &DeviceRegistrationRegisterPostParams{

		Context: ctx,
	}
}

// NewDeviceRegistrationRegisterPostParamsWithHTTPClient creates a new DeviceRegistrationRegisterPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceRegistrationRegisterPostParamsWithHTTPClient(client *http.Client) *DeviceRegistrationRegisterPostParams {
	var ()
	return &DeviceRegistrationRegisterPostParams{
		HTTPClient: client,
	}
}

/*DeviceRegistrationRegisterPostParams contains all the parameters to send to the API endpoint
for the device registration register post operation typically these are written to a http.Request
*/
type DeviceRegistrationRegisterPostParams struct {

	/*Key*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) WithTimeout(timeout time.Duration) *DeviceRegistrationRegisterPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) WithContext(ctx context.Context) *DeviceRegistrationRegisterPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) WithHTTPClient(client *http.Client) *DeviceRegistrationRegisterPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) WithKey(key string) *DeviceRegistrationRegisterPostParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the device registration register post params
func (o *DeviceRegistrationRegisterPostParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceRegistrationRegisterPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
