// Code generated by go-swagger; DO NOT EDIT.

package device_tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeviceRegistrationRegisterPostReader is a Reader for the DeviceRegistrationRegisterPost structure.
type DeviceRegistrationRegisterPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeviceRegistrationRegisterPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeviceRegistrationRegisterPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeviceRegistrationRegisterPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeviceRegistrationRegisterPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeviceRegistrationRegisterPostOK creates a DeviceRegistrationRegisterPostOK with default headers values
func NewDeviceRegistrationRegisterPostOK() *DeviceRegistrationRegisterPostOK {
	return &DeviceRegistrationRegisterPostOK{}
}

/*DeviceRegistrationRegisterPostOK handles this case with default header values.

Success
*/
type DeviceRegistrationRegisterPostOK struct {
}

func (o *DeviceRegistrationRegisterPostOK) Error() string {
	return fmt.Sprintf("[POST /device_registration/register][%d] deviceRegistrationRegisterPostOK ", 200)
}

func (o *DeviceRegistrationRegisterPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeviceRegistrationRegisterPostBadRequest creates a DeviceRegistrationRegisterPostBadRequest with default headers values
func NewDeviceRegistrationRegisterPostBadRequest() *DeviceRegistrationRegisterPostBadRequest {
	return &DeviceRegistrationRegisterPostBadRequest{}
}

/*DeviceRegistrationRegisterPostBadRequest handles this case with default header values.

Bad Request
*/
type DeviceRegistrationRegisterPostBadRequest struct {
}

func (o *DeviceRegistrationRegisterPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /device_registration/register][%d] deviceRegistrationRegisterPostBadRequest ", 400)
}

func (o *DeviceRegistrationRegisterPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeviceRegistrationRegisterPostUnauthorized creates a DeviceRegistrationRegisterPostUnauthorized with default headers values
func NewDeviceRegistrationRegisterPostUnauthorized() *DeviceRegistrationRegisterPostUnauthorized {
	return &DeviceRegistrationRegisterPostUnauthorized{}
}

/*DeviceRegistrationRegisterPostUnauthorized handles this case with default header values.

Unauthorized
*/
type DeviceRegistrationRegisterPostUnauthorized struct {
}

func (o *DeviceRegistrationRegisterPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /device_registration/register][%d] deviceRegistrationRegisterPostUnauthorized ", 401)
}

func (o *DeviceRegistrationRegisterPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
