// Code generated by go-swagger; DO NOT EDIT.

package contract_rules_intervals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// NewContractrulesByRuleIDIntervalsByIntervalIDPutParams creates a new ContractrulesByRuleIDIntervalsByIntervalIDPutParams object
// with the default values initialized.
func NewContractrulesByRuleIDIntervalsByIntervalIDPutParams() *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	var ()
	return &ContractrulesByRuleIDIntervalsByIntervalIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithTimeout creates a new ContractrulesByRuleIDIntervalsByIntervalIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithTimeout(timeout time.Duration) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	var ()
	return &ContractrulesByRuleIDIntervalsByIntervalIDPutParams{

		timeout: timeout,
	}
}

// NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithContext creates a new ContractrulesByRuleIDIntervalsByIntervalIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithContext(ctx context.Context) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	var ()
	return &ContractrulesByRuleIDIntervalsByIntervalIDPutParams{

		Context: ctx,
	}
}

// NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithHTTPClient creates a new ContractrulesByRuleIDIntervalsByIntervalIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContractrulesByRuleIDIntervalsByIntervalIDPutParamsWithHTTPClient(client *http.Client) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	var ()
	return &ContractrulesByRuleIDIntervalsByIntervalIDPutParams{
		HTTPClient: client,
	}
}

/*ContractrulesByRuleIDIntervalsByIntervalIDPutParams contains all the parameters to send to the API endpoint
for the contractrules by rule Id intervals by interval Id put operation typically these are written to a http.Request
*/
type ContractrulesByRuleIDIntervalsByIntervalIDPutParams struct {

	/*IntervalID*/
	IntervalID int64
	/*RuleID*/
	RuleID int64
	/*UpdateModel*/
	UpdateModel *models.ContractRulesIntervalViewModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithTimeout(timeout time.Duration) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithContext(ctx context.Context) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithHTTPClient(client *http.Client) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntervalID adds the intervalID to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithIntervalID(intervalID int64) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetIntervalID(intervalID)
	return o
}

// SetIntervalID adds the intervalId to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetIntervalID(intervalID int64) {
	o.IntervalID = intervalID
}

// WithRuleID adds the ruleID to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithRuleID(ruleID int64) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetRuleID(ruleID int64) {
	o.RuleID = ruleID
}

// WithUpdateModel adds the updateModel to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WithUpdateModel(updateModel *models.ContractRulesIntervalViewModel) *ContractrulesByRuleIDIntervalsByIntervalIDPutParams {
	o.SetUpdateModel(updateModel)
	return o
}

// SetUpdateModel adds the updateModel to the contractrules by rule Id intervals by interval Id put params
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) SetUpdateModel(updateModel *models.ContractRulesIntervalViewModel) {
	o.UpdateModel = updateModel
}

// WriteToRequest writes these params to a swagger request
func (o *ContractrulesByRuleIDIntervalsByIntervalIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param intervalId
	if err := r.SetPathParam("intervalId", swag.FormatInt64(o.IntervalID)); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", swag.FormatInt64(o.RuleID)); err != nil {
		return err
	}

	if o.UpdateModel != nil {
		if err := r.SetBodyParam(o.UpdateModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
