// Code generated by go-swagger; DO NOT EDIT.

package contract_rules_shift_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContractrulesByRuleIDShifttypesGetParams creates a new ContractrulesByRuleIDShifttypesGetParams object
// with the default values initialized.
func NewContractrulesByRuleIDShifttypesGetParams() *ContractrulesByRuleIDShifttypesGetParams {
	var ()
	return &ContractrulesByRuleIDShifttypesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContractrulesByRuleIDShifttypesGetParamsWithTimeout creates a new ContractrulesByRuleIDShifttypesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContractrulesByRuleIDShifttypesGetParamsWithTimeout(timeout time.Duration) *ContractrulesByRuleIDShifttypesGetParams {
	var ()
	return &ContractrulesByRuleIDShifttypesGetParams{

		timeout: timeout,
	}
}

// NewContractrulesByRuleIDShifttypesGetParamsWithContext creates a new ContractrulesByRuleIDShifttypesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewContractrulesByRuleIDShifttypesGetParamsWithContext(ctx context.Context) *ContractrulesByRuleIDShifttypesGetParams {
	var ()
	return &ContractrulesByRuleIDShifttypesGetParams{

		Context: ctx,
	}
}

// NewContractrulesByRuleIDShifttypesGetParamsWithHTTPClient creates a new ContractrulesByRuleIDShifttypesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContractrulesByRuleIDShifttypesGetParamsWithHTTPClient(client *http.Client) *ContractrulesByRuleIDShifttypesGetParams {
	var ()
	return &ContractrulesByRuleIDShifttypesGetParams{
		HTTPClient: client,
	}
}

/*ContractrulesByRuleIDShifttypesGetParams contains all the parameters to send to the API endpoint
for the contractrules by rule Id shifttypes get operation typically these are written to a http.Request
*/
type ContractrulesByRuleIDShifttypesGetParams struct {

	/*RuleID*/
	RuleID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) WithTimeout(timeout time.Duration) *ContractrulesByRuleIDShifttypesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) WithContext(ctx context.Context) *ContractrulesByRuleIDShifttypesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) WithHTTPClient(client *http.Client) *ContractrulesByRuleIDShifttypesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) WithRuleID(ruleID int64) *ContractrulesByRuleIDShifttypesGetParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the contractrules by rule Id shifttypes get params
func (o *ContractrulesByRuleIDShifttypesGetParams) SetRuleID(ruleID int64) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *ContractrulesByRuleIDShifttypesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", swag.FormatInt64(o.RuleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
