// Code generated by go-swagger; DO NOT EDIT.

package employees_relations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeesByIDRelationsPutReader is a Reader for the EmployeesByIDRelationsPut structure.
type EmployeesByIDRelationsPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDRelationsPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDRelationsPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDRelationsPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDRelationsPutOK creates a EmployeesByIDRelationsPutOK with default headers values
func NewEmployeesByIDRelationsPutOK() *EmployeesByIDRelationsPutOK {
	return &EmployeesByIDRelationsPutOK{}
}

/*EmployeesByIDRelationsPutOK handles this case with default header values.

Success
*/
type EmployeesByIDRelationsPutOK struct {
	Payload *models.EmployeeViewModel
}

func (o *EmployeesByIDRelationsPutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/relations][%d] employeesByIdRelationsPutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDRelationsPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDRelationsPutUnauthorized creates a EmployeesByIDRelationsPutUnauthorized with default headers values
func NewEmployeesByIDRelationsPutUnauthorized() *EmployeesByIDRelationsPutUnauthorized {
	return &EmployeesByIDRelationsPutUnauthorized{}
}

/*EmployeesByIDRelationsPutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDRelationsPutUnauthorized struct {
}

func (o *EmployeesByIDRelationsPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/relations][%d] employeesByIdRelationsPutUnauthorized ", 401)
}

func (o *EmployeesByIDRelationsPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
