// Code generated by go-swagger; DO NOT EDIT.

package translations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TranslationsMissingPostReader is a Reader for the TranslationsMissingPost structure.
type TranslationsMissingPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TranslationsMissingPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTranslationsMissingPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTranslationsMissingPostOK creates a TranslationsMissingPostOK with default headers values
func NewTranslationsMissingPostOK() *TranslationsMissingPostOK {
	return &TranslationsMissingPostOK{}
}

/*TranslationsMissingPostOK handles this case with default header values.

Success
*/
type TranslationsMissingPostOK struct {
}

func (o *TranslationsMissingPostOK) Error() string {
	return fmt.Sprintf("[POST /translations/missing][%d] translationsMissingPostOK ", 200)
}

func (o *TranslationsMissingPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
