// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// RolesByIDPutReader is a Reader for the RolesByIDPut structure.
type RolesByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RolesByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRolesByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewRolesByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRolesByIDPutOK creates a RolesByIDPutOK with default headers values
func NewRolesByIDPutOK() *RolesByIDPutOK {
	return &RolesByIDPutOK{}
}

/*RolesByIDPutOK handles this case with default header values.

Success
*/
type RolesByIDPutOK struct {
	Payload *models.EmployeeGroupViewModel
}

func (o *RolesByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /roles/{id}][%d] rolesByIdPutOK  %+v", 200, o.Payload)
}

func (o *RolesByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeGroupViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRolesByIDPutUnauthorized creates a RolesByIDPutUnauthorized with default headers values
func NewRolesByIDPutUnauthorized() *RolesByIDPutUnauthorized {
	return &RolesByIDPutUnauthorized{}
}

/*RolesByIDPutUnauthorized handles this case with default header values.

Unauthorized
*/
type RolesByIDPutUnauthorized struct {
}

func (o *RolesByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /roles/{id}][%d] rolesByIdPutUnauthorized ", 401)
}

func (o *RolesByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
