// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// RolesByIDGetReader is a Reader for the RolesByIDGet structure.
type RolesByIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RolesByIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRolesByIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewRolesByIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRolesByIDGetOK creates a RolesByIDGetOK with default headers values
func NewRolesByIDGetOK() *RolesByIDGetOK {
	return &RolesByIDGetOK{}
}

/*RolesByIDGetOK handles this case with default header values.

Success
*/
type RolesByIDGetOK struct {
	Payload *models.EmployeeGroupViewModelExtended
}

func (o *RolesByIDGetOK) Error() string {
	return fmt.Sprintf("[GET /roles/{id}][%d] rolesByIdGetOK  %+v", 200, o.Payload)
}

func (o *RolesByIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeGroupViewModelExtended)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRolesByIDGetUnauthorized creates a RolesByIDGetUnauthorized with default headers values
func NewRolesByIDGetUnauthorized() *RolesByIDGetUnauthorized {
	return &RolesByIDGetUnauthorized{}
}

/*RolesByIDGetUnauthorized handles this case with default header values.

Unauthorized
*/
type RolesByIDGetUnauthorized struct {
}

func (o *RolesByIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /roles/{id}][%d] rolesByIdGetUnauthorized ", 401)
}

func (o *RolesByIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
