// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSystemErrorsGetParams creates a new SystemErrorsGetParams object
// with the default values initialized.
func NewSystemErrorsGetParams() *SystemErrorsGetParams {

	return &SystemErrorsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSystemErrorsGetParamsWithTimeout creates a new SystemErrorsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSystemErrorsGetParamsWithTimeout(timeout time.Duration) *SystemErrorsGetParams {

	return &SystemErrorsGetParams{

		timeout: timeout,
	}
}

// NewSystemErrorsGetParamsWithContext creates a new SystemErrorsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSystemErrorsGetParamsWithContext(ctx context.Context) *SystemErrorsGetParams {

	return &SystemErrorsGetParams{

		Context: ctx,
	}
}

// NewSystemErrorsGetParamsWithHTTPClient creates a new SystemErrorsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSystemErrorsGetParamsWithHTTPClient(client *http.Client) *SystemErrorsGetParams {

	return &SystemErrorsGetParams{
		HTTPClient: client,
	}
}

/*SystemErrorsGetParams contains all the parameters to send to the API endpoint
for the system errors get operation typically these are written to a http.Request
*/
type SystemErrorsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the system errors get params
func (o *SystemErrorsGetParams) WithTimeout(timeout time.Duration) *SystemErrorsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system errors get params
func (o *SystemErrorsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system errors get params
func (o *SystemErrorsGetParams) WithContext(ctx context.Context) *SystemErrorsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system errors get params
func (o *SystemErrorsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system errors get params
func (o *SystemErrorsGetParams) WithHTTPClient(client *http.Client) *SystemErrorsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system errors get params
func (o *SystemErrorsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SystemErrorsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
