// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// SystemPhonePrefixesGetReader is a Reader for the SystemPhonePrefixesGet structure.
type SystemPhonePrefixesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemPhonePrefixesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSystemPhonePrefixesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemPhonePrefixesGetOK creates a SystemPhonePrefixesGetOK with default headers values
func NewSystemPhonePrefixesGetOK() *SystemPhonePrefixesGetOK {
	return &SystemPhonePrefixesGetOK{}
}

/*SystemPhonePrefixesGetOK handles this case with default header values.

Success
*/
type SystemPhonePrefixesGetOK struct {
	Payload []*models.PhoneViewModel
}

func (o *SystemPhonePrefixesGetOK) Error() string {
	return fmt.Sprintf("[GET /system/phone_prefixes][%d] systemPhonePrefixesGetOK  %+v", 200, o.Payload)
}

func (o *SystemPhonePrefixesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
