// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// SystemErrorsGetReader is a Reader for the SystemErrorsGet structure.
type SystemErrorsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemErrorsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSystemErrorsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemErrorsGetOK creates a SystemErrorsGetOK with default headers values
func NewSystemErrorsGetOK() *SystemErrorsGetOK {
	return &SystemErrorsGetOK{}
}

/*SystemErrorsGetOK handles this case with default header values.

Success
*/
type SystemErrorsGetOK struct {
	Payload []*models.ExceptionInfo
}

func (o *SystemErrorsGetOK) Error() string {
	return fmt.Sprintf("[GET /system/errors][%d] systemErrorsGetOK  %+v", 200, o.Payload)
}

func (o *SystemErrorsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
