// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// InvitesPostReader is a Reader for the InvitesPost structure.
type InvitesPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InvitesPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInvitesPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewInvitesPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInvitesPostOK creates a InvitesPostOK with default headers values
func NewInvitesPostOK() *InvitesPostOK {
	return &InvitesPostOK{}
}

/*InvitesPostOK handles this case with default header values.

Success
*/
type InvitesPostOK struct {
	Payload []*models.InviteViewModel
}

func (o *InvitesPostOK) Error() string {
	return fmt.Sprintf("[POST /invites][%d] invitesPostOK  %+v", 200, o.Payload)
}

func (o *InvitesPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInvitesPostUnauthorized creates a InvitesPostUnauthorized with default headers values
func NewInvitesPostUnauthorized() *InvitesPostUnauthorized {
	return &InvitesPostUnauthorized{}
}

/*InvitesPostUnauthorized handles this case with default header values.

Unauthorized
*/
type InvitesPostUnauthorized struct {
}

func (o *InvitesPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /invites][%d] invitesPostUnauthorized ", 401)
}

func (o *InvitesPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
