// Code generated by go-swagger; DO NOT EDIT.

package employee_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeeGroupsGetParams creates a new EmployeeGroupsGetParams object
// with the default values initialized.
func NewEmployeeGroupsGetParams() *EmployeeGroupsGetParams {
	var ()
	return &EmployeeGroupsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeeGroupsGetParamsWithTimeout creates a new EmployeeGroupsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeeGroupsGetParamsWithTimeout(timeout time.Duration) *EmployeeGroupsGetParams {
	var ()
	return &EmployeeGroupsGetParams{

		timeout: timeout,
	}
}

// NewEmployeeGroupsGetParamsWithContext creates a new EmployeeGroupsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeeGroupsGetParamsWithContext(ctx context.Context) *EmployeeGroupsGetParams {
	var ()
	return &EmployeeGroupsGetParams{

		Context: ctx,
	}
}

// NewEmployeeGroupsGetParamsWithHTTPClient creates a new EmployeeGroupsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeeGroupsGetParamsWithHTTPClient(client *http.Client) *EmployeeGroupsGetParams {
	var ()
	return &EmployeeGroupsGetParams{
		HTTPClient: client,
	}
}

/*EmployeeGroupsGetParams contains all the parameters to send to the API endpoint
for the employee groups get operation typically these are written to a http.Request
*/
type EmployeeGroupsGetParams struct {

	/*DepartmentID*/
	DepartmentID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employee groups get params
func (o *EmployeeGroupsGetParams) WithTimeout(timeout time.Duration) *EmployeeGroupsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employee groups get params
func (o *EmployeeGroupsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employee groups get params
func (o *EmployeeGroupsGetParams) WithContext(ctx context.Context) *EmployeeGroupsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employee groups get params
func (o *EmployeeGroupsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employee groups get params
func (o *EmployeeGroupsGetParams) WithHTTPClient(client *http.Client) *EmployeeGroupsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employee groups get params
func (o *EmployeeGroupsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDepartmentID adds the departmentID to the employee groups get params
func (o *EmployeeGroupsGetParams) WithDepartmentID(departmentID *int64) *EmployeeGroupsGetParams {
	o.SetDepartmentID(departmentID)
	return o
}

// SetDepartmentID adds the departmentId to the employee groups get params
func (o *EmployeeGroupsGetParams) SetDepartmentID(departmentID *int64) {
	o.DepartmentID = departmentID
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeeGroupsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DepartmentID != nil {

		// query param department_id
		var qrDepartmentID int64
		if o.DepartmentID != nil {
			qrDepartmentID = *o.DepartmentID
		}
		qDepartmentID := swag.FormatInt64(qrDepartmentID)
		if qDepartmentID != "" {
			if err := r.SetQueryParam("department_id", qDepartmentID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
