// Code generated by go-swagger; DO NOT EDIT.

package employee_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeeGroupsByIDPutReader is a Reader for the EmployeeGroupsByIDPut structure.
type EmployeeGroupsByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeeGroupsByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeeGroupsByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeeGroupsByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeeGroupsByIDPutOK creates a EmployeeGroupsByIDPutOK with default headers values
func NewEmployeeGroupsByIDPutOK() *EmployeeGroupsByIDPutOK {
	return &EmployeeGroupsByIDPutOK{}
}

/*EmployeeGroupsByIDPutOK handles this case with default header values.

Success
*/
type EmployeeGroupsByIDPutOK struct {
	Payload *models.EmployeeGroupViewModel
}

func (o *EmployeeGroupsByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /employee_groups/{id}][%d] employeeGroupsByIdPutOK  %+v", 200, o.Payload)
}

func (o *EmployeeGroupsByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeGroupViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeeGroupsByIDPutUnauthorized creates a EmployeeGroupsByIDPutUnauthorized with default headers values
func NewEmployeeGroupsByIDPutUnauthorized() *EmployeeGroupsByIDPutUnauthorized {
	return &EmployeeGroupsByIDPutUnauthorized{}
}

/*EmployeeGroupsByIDPutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeeGroupsByIDPutUnauthorized struct {
}

func (o *EmployeeGroupsByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employee_groups/{id}][%d] employeeGroupsByIdPutUnauthorized ", 401)
}

func (o *EmployeeGroupsByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
