// Code generated by go-swagger; DO NOT EDIT.

package employee_priorities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeePrioritiesByIDPutReader is a Reader for the EmployeePrioritiesByIDPut structure.
type EmployeePrioritiesByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeePrioritiesByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 401:
		result := NewEmployeePrioritiesByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeePrioritiesByIDPutUnauthorized creates a EmployeePrioritiesByIDPutUnauthorized with default headers values
func NewEmployeePrioritiesByIDPutUnauthorized() *EmployeePrioritiesByIDPutUnauthorized {
	return &EmployeePrioritiesByIDPutUnauthorized{}
}

/*EmployeePrioritiesByIDPutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeePrioritiesByIDPutUnauthorized struct {
}

func (o *EmployeePrioritiesByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employee_priorities/{id}][%d] employeePrioritiesByIdPutUnauthorized ", 401)
}

func (o *EmployeePrioritiesByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
