// Code generated by go-swagger; DO NOT EDIT.

package employee_priorities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeePrioritiesGetReader is a Reader for the EmployeePrioritiesGet structure.
type EmployeePrioritiesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeePrioritiesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeePrioritiesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeePrioritiesGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeePrioritiesGetOK creates a EmployeePrioritiesGetOK with default headers values
func NewEmployeePrioritiesGetOK() *EmployeePrioritiesGetOK {
	return &EmployeePrioritiesGetOK{}
}

/*EmployeePrioritiesGetOK handles this case with default header values.

Success
*/
type EmployeePrioritiesGetOK struct {
	Payload []*models.EmployeePriorityViewModel
}

func (o *EmployeePrioritiesGetOK) Error() string {
	return fmt.Sprintf("[GET /employee_priorities][%d] employeePrioritiesGetOK  %+v", 200, o.Payload)
}

func (o *EmployeePrioritiesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeePrioritiesGetUnauthorized creates a EmployeePrioritiesGetUnauthorized with default headers values
func NewEmployeePrioritiesGetUnauthorized() *EmployeePrioritiesGetUnauthorized {
	return &EmployeePrioritiesGetUnauthorized{}
}

/*EmployeePrioritiesGetUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeePrioritiesGetUnauthorized struct {
}

func (o *EmployeePrioritiesGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employee_priorities][%d] employeePrioritiesGetUnauthorized ", 401)
}

func (o *EmployeePrioritiesGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
