// Code generated by go-swagger; DO NOT EDIT.

package employee_priorities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeePrioritiesGetParams creates a new EmployeePrioritiesGetParams object
// with the default values initialized.
func NewEmployeePrioritiesGetParams() *EmployeePrioritiesGetParams {
	var ()
	return &EmployeePrioritiesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeePrioritiesGetParamsWithTimeout creates a new EmployeePrioritiesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeePrioritiesGetParamsWithTimeout(timeout time.Duration) *EmployeePrioritiesGetParams {
	var ()
	return &EmployeePrioritiesGetParams{

		timeout: timeout,
	}
}

// NewEmployeePrioritiesGetParamsWithContext creates a new EmployeePrioritiesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeePrioritiesGetParamsWithContext(ctx context.Context) *EmployeePrioritiesGetParams {
	var ()
	return &EmployeePrioritiesGetParams{

		Context: ctx,
	}
}

// NewEmployeePrioritiesGetParamsWithHTTPClient creates a new EmployeePrioritiesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeePrioritiesGetParamsWithHTTPClient(client *http.Client) *EmployeePrioritiesGetParams {
	var ()
	return &EmployeePrioritiesGetParams{
		HTTPClient: client,
	}
}

/*EmployeePrioritiesGetParams contains all the parameters to send to the API endpoint
for the employee priorities get operation typically these are written to a http.Request
*/
type EmployeePrioritiesGetParams struct {

	/*DepartmentID*/
	DepartmentID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employee priorities get params
func (o *EmployeePrioritiesGetParams) WithTimeout(timeout time.Duration) *EmployeePrioritiesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employee priorities get params
func (o *EmployeePrioritiesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employee priorities get params
func (o *EmployeePrioritiesGetParams) WithContext(ctx context.Context) *EmployeePrioritiesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employee priorities get params
func (o *EmployeePrioritiesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employee priorities get params
func (o *EmployeePrioritiesGetParams) WithHTTPClient(client *http.Client) *EmployeePrioritiesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employee priorities get params
func (o *EmployeePrioritiesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDepartmentID adds the departmentID to the employee priorities get params
func (o *EmployeePrioritiesGetParams) WithDepartmentID(departmentID *int64) *EmployeePrioritiesGetParams {
	o.SetDepartmentID(departmentID)
	return o
}

// SetDepartmentID adds the departmentId to the employee priorities get params
func (o *EmployeePrioritiesGetParams) SetDepartmentID(departmentID *int64) {
	o.DepartmentID = departmentID
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeePrioritiesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DepartmentID != nil {

		// query param departmentId
		var qrDepartmentID int64
		if o.DepartmentID != nil {
			qrDepartmentID = *o.DepartmentID
		}
		qDepartmentID := swag.FormatInt64(qrDepartmentID)
		if qDepartmentID != "" {
			if err := r.SetQueryParam("departmentId", qDepartmentID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
