// Code generated by go-swagger; DO NOT EDIT.

package employees_columns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeesAllcolumnsGetReader is a Reader for the EmployeesAllcolumnsGet structure.
type EmployeesAllcolumnsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesAllcolumnsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesAllcolumnsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesAllcolumnsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesAllcolumnsGetOK creates a EmployeesAllcolumnsGetOK with default headers values
func NewEmployeesAllcolumnsGetOK() *EmployeesAllcolumnsGetOK {
	return &EmployeesAllcolumnsGetOK{}
}

/*EmployeesAllcolumnsGetOK handles this case with default header values.

Success
*/
type EmployeesAllcolumnsGetOK struct {
	Payload *models.EmployeeColumnViewModel
}

func (o *EmployeesAllcolumnsGetOK) Error() string {
	return fmt.Sprintf("[GET /employees/allcolumns][%d] employeesAllcolumnsGetOK  %+v", 200, o.Payload)
}

func (o *EmployeesAllcolumnsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeColumnViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesAllcolumnsGetUnauthorized creates a EmployeesAllcolumnsGetUnauthorized with default headers values
func NewEmployeesAllcolumnsGetUnauthorized() *EmployeesAllcolumnsGetUnauthorized {
	return &EmployeesAllcolumnsGetUnauthorized{}
}

/*EmployeesAllcolumnsGetUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesAllcolumnsGetUnauthorized struct {
}

func (o *EmployeesAllcolumnsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employees/allcolumns][%d] employeesAllcolumnsGetUnauthorized ", 401)
}

func (o *EmployeesAllcolumnsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
