// Code generated by go-swagger; DO NOT EDIT.

package employees_contract_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeesByIDContractrulePutReader is a Reader for the EmployeesByIDContractrulePut structure.
type EmployeesByIDContractrulePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDContractrulePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDContractrulePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDContractrulePutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDContractrulePutOK creates a EmployeesByIDContractrulePutOK with default headers values
func NewEmployeesByIDContractrulePutOK() *EmployeesByIDContractrulePutOK {
	return &EmployeesByIDContractrulePutOK{}
}

/*EmployeesByIDContractrulePutOK handles this case with default header values.

Success
*/
type EmployeesByIDContractrulePutOK struct {
	Payload *models.EmployeeViewModel
}

func (o *EmployeesByIDContractrulePutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/contractrule][%d] employeesByIdContractrulePutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDContractrulePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmployeeViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDContractrulePutUnauthorized creates a EmployeesByIDContractrulePutUnauthorized with default headers values
func NewEmployeesByIDContractrulePutUnauthorized() *EmployeesByIDContractrulePutUnauthorized {
	return &EmployeesByIDContractrulePutUnauthorized{}
}

/*EmployeesByIDContractrulePutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDContractrulePutUnauthorized struct {
}

func (o *EmployeesByIDContractrulePutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/contractrule][%d] employeesByIdContractrulePutUnauthorized ", 401)
}

func (o *EmployeesByIDContractrulePutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
