// Code generated by go-swagger; DO NOT EDIT.

package employees_user_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesByIDSendWelcomeMessagePutParams creates a new EmployeesByIDSendWelcomeMessagePutParams object
// with the default values initialized.
func NewEmployeesByIDSendWelcomeMessagePutParams() *EmployeesByIDSendWelcomeMessagePutParams {
	var ()
	return &EmployeesByIDSendWelcomeMessagePutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesByIDSendWelcomeMessagePutParamsWithTimeout creates a new EmployeesByIDSendWelcomeMessagePutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesByIDSendWelcomeMessagePutParamsWithTimeout(timeout time.Duration) *EmployeesByIDSendWelcomeMessagePutParams {
	var ()
	return &EmployeesByIDSendWelcomeMessagePutParams{

		timeout: timeout,
	}
}

// NewEmployeesByIDSendWelcomeMessagePutParamsWithContext creates a new EmployeesByIDSendWelcomeMessagePutParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesByIDSendWelcomeMessagePutParamsWithContext(ctx context.Context) *EmployeesByIDSendWelcomeMessagePutParams {
	var ()
	return &EmployeesByIDSendWelcomeMessagePutParams{

		Context: ctx,
	}
}

// NewEmployeesByIDSendWelcomeMessagePutParamsWithHTTPClient creates a new EmployeesByIDSendWelcomeMessagePutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesByIDSendWelcomeMessagePutParamsWithHTTPClient(client *http.Client) *EmployeesByIDSendWelcomeMessagePutParams {
	var ()
	return &EmployeesByIDSendWelcomeMessagePutParams{
		HTTPClient: client,
	}
}

/*EmployeesByIDSendWelcomeMessagePutParams contains all the parameters to send to the API endpoint
for the employees by Id send welcome message put operation typically these are written to a http.Request
*/
type EmployeesByIDSendWelcomeMessagePutParams struct {

	/*ID
	  The id of employee to send the welcome mail

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) WithTimeout(timeout time.Duration) *EmployeesByIDSendWelcomeMessagePutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) WithContext(ctx context.Context) *EmployeesByIDSendWelcomeMessagePutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) WithHTTPClient(client *http.Client) *EmployeesByIDSendWelcomeMessagePutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) WithID(id int64) *EmployeesByIDSendWelcomeMessagePutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employees by Id send welcome message put params
func (o *EmployeesByIDSendWelcomeMessagePutParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesByIDSendWelcomeMessagePutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
