// Code generated by go-swagger; DO NOT EDIT.

package employees_user_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDSendSmsWelcomeMessagePutReader is a Reader for the EmployeesByIDSendSmsWelcomeMessagePut structure.
type EmployeesByIDSendSmsWelcomeMessagePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDSendSmsWelcomeMessagePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDSendSmsWelcomeMessagePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDSendSmsWelcomeMessagePutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDSendSmsWelcomeMessagePutOK creates a EmployeesByIDSendSmsWelcomeMessagePutOK with default headers values
func NewEmployeesByIDSendSmsWelcomeMessagePutOK() *EmployeesByIDSendSmsWelcomeMessagePutOK {
	return &EmployeesByIDSendSmsWelcomeMessagePutOK{}
}

/*EmployeesByIDSendSmsWelcomeMessagePutOK handles this case with default header values.

Success
*/
type EmployeesByIDSendSmsWelcomeMessagePutOK struct {
	Payload bool
}

func (o *EmployeesByIDSendSmsWelcomeMessagePutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/send_sms_welcome_message][%d] employeesByIdSendSmsWelcomeMessagePutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDSendSmsWelcomeMessagePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDSendSmsWelcomeMessagePutUnauthorized creates a EmployeesByIDSendSmsWelcomeMessagePutUnauthorized with default headers values
func NewEmployeesByIDSendSmsWelcomeMessagePutUnauthorized() *EmployeesByIDSendSmsWelcomeMessagePutUnauthorized {
	return &EmployeesByIDSendSmsWelcomeMessagePutUnauthorized{}
}

/*EmployeesByIDSendSmsWelcomeMessagePutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDSendSmsWelcomeMessagePutUnauthorized struct {
}

func (o *EmployeesByIDSendSmsWelcomeMessagePutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/send_sms_welcome_message][%d] employeesByIdSendSmsWelcomeMessagePutUnauthorized ", 401)
}

func (o *EmployeesByIDSendSmsWelcomeMessagePutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
