// Code generated by go-swagger; DO NOT EDIT.

package employees_user_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDResetPasswordPutReader is a Reader for the EmployeesByIDResetPasswordPut structure.
type EmployeesByIDResetPasswordPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDResetPasswordPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDResetPasswordPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDResetPasswordPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDResetPasswordPutOK creates a EmployeesByIDResetPasswordPutOK with default headers values
func NewEmployeesByIDResetPasswordPutOK() *EmployeesByIDResetPasswordPutOK {
	return &EmployeesByIDResetPasswordPutOK{}
}

/*EmployeesByIDResetPasswordPutOK handles this case with default header values.

Success
*/
type EmployeesByIDResetPasswordPutOK struct {
	Payload bool
}

func (o *EmployeesByIDResetPasswordPutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/reset_password][%d] employeesByIdResetPasswordPutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDResetPasswordPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDResetPasswordPutUnauthorized creates a EmployeesByIDResetPasswordPutUnauthorized with default headers values
func NewEmployeesByIDResetPasswordPutUnauthorized() *EmployeesByIDResetPasswordPutUnauthorized {
	return &EmployeesByIDResetPasswordPutUnauthorized{}
}

/*EmployeesByIDResetPasswordPutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDResetPasswordPutUnauthorized struct {
}

func (o *EmployeesByIDResetPasswordPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/reset_password][%d] employeesByIdResetPasswordPutUnauthorized ", 401)
}

func (o *EmployeesByIDResetPasswordPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
