// Code generated by go-swagger; DO NOT EDIT.

package employees_user_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesUsernameInUseGetReader is a Reader for the EmployeesUsernameInUseGet structure.
type EmployeesUsernameInUseGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesUsernameInUseGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesUsernameInUseGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesUsernameInUseGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesUsernameInUseGetOK creates a EmployeesUsernameInUseGetOK with default headers values
func NewEmployeesUsernameInUseGetOK() *EmployeesUsernameInUseGetOK {
	return &EmployeesUsernameInUseGetOK{}
}

/*EmployeesUsernameInUseGetOK handles this case with default header values.

Success
*/
type EmployeesUsernameInUseGetOK struct {
	Payload bool
}

func (o *EmployeesUsernameInUseGetOK) Error() string {
	return fmt.Sprintf("[GET /employees/username_in_use][%d] employeesUsernameInUseGetOK  %+v", 200, o.Payload)
}

func (o *EmployeesUsernameInUseGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesUsernameInUseGetUnauthorized creates a EmployeesUsernameInUseGetUnauthorized with default headers values
func NewEmployeesUsernameInUseGetUnauthorized() *EmployeesUsernameInUseGetUnauthorized {
	return &EmployeesUsernameInUseGetUnauthorized{}
}

/*EmployeesUsernameInUseGetUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesUsernameInUseGetUnauthorized struct {
}

func (o *EmployeesUsernameInUseGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employees/username_in_use][%d] employeesUsernameInUseGetUnauthorized ", 401)
}

func (o *EmployeesUsernameInUseGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
