// Code generated by go-swagger; DO NOT EDIT.

package employees_user_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDSendWelcomeMessagePutReader is a Reader for the EmployeesByIDSendWelcomeMessagePut structure.
type EmployeesByIDSendWelcomeMessagePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDSendWelcomeMessagePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDSendWelcomeMessagePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDSendWelcomeMessagePutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDSendWelcomeMessagePutOK creates a EmployeesByIDSendWelcomeMessagePutOK with default headers values
func NewEmployeesByIDSendWelcomeMessagePutOK() *EmployeesByIDSendWelcomeMessagePutOK {
	return &EmployeesByIDSendWelcomeMessagePutOK{}
}

/*EmployeesByIDSendWelcomeMessagePutOK handles this case with default header values.

Success
*/
type EmployeesByIDSendWelcomeMessagePutOK struct {
	Payload bool
}

func (o *EmployeesByIDSendWelcomeMessagePutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/send_welcome_message][%d] employeesByIdSendWelcomeMessagePutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDSendWelcomeMessagePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDSendWelcomeMessagePutUnauthorized creates a EmployeesByIDSendWelcomeMessagePutUnauthorized with default headers values
func NewEmployeesByIDSendWelcomeMessagePutUnauthorized() *EmployeesByIDSendWelcomeMessagePutUnauthorized {
	return &EmployeesByIDSendWelcomeMessagePutUnauthorized{}
}

/*EmployeesByIDSendWelcomeMessagePutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDSendWelcomeMessagePutUnauthorized struct {
}

func (o *EmployeesByIDSendWelcomeMessagePutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/send_welcome_message][%d] employeesByIdSendWelcomeMessagePutUnauthorized ", 401)
}

func (o *EmployeesByIDSendWelcomeMessagePutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
