// Code generated by go-swagger; DO NOT EDIT.

package gdpr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGdprPortalsRtbfStatusGetParams creates a new GdprPortalsRtbfStatusGetParams object
// with the default values initialized.
func NewGdprPortalsRtbfStatusGetParams() *GdprPortalsRtbfStatusGetParams {

	return &GdprPortalsRtbfStatusGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGdprPortalsRtbfStatusGetParamsWithTimeout creates a new GdprPortalsRtbfStatusGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGdprPortalsRtbfStatusGetParamsWithTimeout(timeout time.Duration) *GdprPortalsRtbfStatusGetParams {

	return &GdprPortalsRtbfStatusGetParams{

		timeout: timeout,
	}
}

// NewGdprPortalsRtbfStatusGetParamsWithContext creates a new GdprPortalsRtbfStatusGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewGdprPortalsRtbfStatusGetParamsWithContext(ctx context.Context) *GdprPortalsRtbfStatusGetParams {

	return &GdprPortalsRtbfStatusGetParams{

		Context: ctx,
	}
}

// NewGdprPortalsRtbfStatusGetParamsWithHTTPClient creates a new GdprPortalsRtbfStatusGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGdprPortalsRtbfStatusGetParamsWithHTTPClient(client *http.Client) *GdprPortalsRtbfStatusGetParams {

	return &GdprPortalsRtbfStatusGetParams{
		HTTPClient: client,
	}
}

/*GdprPortalsRtbfStatusGetParams contains all the parameters to send to the API endpoint
for the gdpr portals rtbf status get operation typically these are written to a http.Request
*/
type GdprPortalsRtbfStatusGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) WithTimeout(timeout time.Duration) *GdprPortalsRtbfStatusGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) WithContext(ctx context.Context) *GdprPortalsRtbfStatusGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) WithHTTPClient(client *http.Client) *GdprPortalsRtbfStatusGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the gdpr portals rtbf status get params
func (o *GdprPortalsRtbfStatusGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GdprPortalsRtbfStatusGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
