// Code generated by go-swagger; DO NOT EDIT.

package gdpr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// GdprPortalsByPortalAliasGdprStatusGetReader is a Reader for the GdprPortalsByPortalAliasGdprStatusGet structure.
type GdprPortalsByPortalAliasGdprStatusGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GdprPortalsByPortalAliasGdprStatusGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGdprPortalsByPortalAliasGdprStatusGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGdprPortalsByPortalAliasGdprStatusGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGdprPortalsByPortalAliasGdprStatusGetOK creates a GdprPortalsByPortalAliasGdprStatusGetOK with default headers values
func NewGdprPortalsByPortalAliasGdprStatusGetOK() *GdprPortalsByPortalAliasGdprStatusGetOK {
	return &GdprPortalsByPortalAliasGdprStatusGetOK{}
}

/*GdprPortalsByPortalAliasGdprStatusGetOK handles this case with default header values.

Success
*/
type GdprPortalsByPortalAliasGdprStatusGetOK struct {
	Payload *models.GdprStatusResult
}

func (o *GdprPortalsByPortalAliasGdprStatusGetOK) Error() string {
	return fmt.Sprintf("[GET /gdpr/portals/{portal_alias}/gdpr_status][%d] gdprPortalsByPortalAliasGdprStatusGetOK  %+v", 200, o.Payload)
}

func (o *GdprPortalsByPortalAliasGdprStatusGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GdprStatusResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGdprPortalsByPortalAliasGdprStatusGetUnauthorized creates a GdprPortalsByPortalAliasGdprStatusGetUnauthorized with default headers values
func NewGdprPortalsByPortalAliasGdprStatusGetUnauthorized() *GdprPortalsByPortalAliasGdprStatusGetUnauthorized {
	return &GdprPortalsByPortalAliasGdprStatusGetUnauthorized{}
}

/*GdprPortalsByPortalAliasGdprStatusGetUnauthorized handles this case with default header values.

Unauthorized
*/
type GdprPortalsByPortalAliasGdprStatusGetUnauthorized struct {
}

func (o *GdprPortalsByPortalAliasGdprStatusGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /gdpr/portals/{portal_alias}/gdpr_status][%d] gdprPortalsByPortalAliasGdprStatusGetUnauthorized ", 401)
}

func (o *GdprPortalsByPortalAliasGdprStatusGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
