// Code generated by go-swagger; DO NOT EDIT.

package portal_employee_form_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// PortalsByPortalIDFormsEmployeeGetReader is a Reader for the PortalsByPortalIDFormsEmployeeGet structure.
type PortalsByPortalIDFormsEmployeeGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PortalsByPortalIDFormsEmployeeGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPortalsByPortalIDFormsEmployeeGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPortalsByPortalIDFormsEmployeeGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPortalsByPortalIDFormsEmployeeGetOK creates a PortalsByPortalIDFormsEmployeeGetOK with default headers values
func NewPortalsByPortalIDFormsEmployeeGetOK() *PortalsByPortalIDFormsEmployeeGetOK {
	return &PortalsByPortalIDFormsEmployeeGetOK{}
}

/*PortalsByPortalIDFormsEmployeeGetOK handles this case with default header values.

Success
*/
type PortalsByPortalIDFormsEmployeeGetOK struct {
	Payload *models.FormDefinitionResult
}

func (o *PortalsByPortalIDFormsEmployeeGetOK) Error() string {
	return fmt.Sprintf("[GET /portals/{portal_id}/forms/employee][%d] portalsByPortalIdFormsEmployeeGetOK  %+v", 200, o.Payload)
}

func (o *PortalsByPortalIDFormsEmployeeGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FormDefinitionResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPortalsByPortalIDFormsEmployeeGetUnauthorized creates a PortalsByPortalIDFormsEmployeeGetUnauthorized with default headers values
func NewPortalsByPortalIDFormsEmployeeGetUnauthorized() *PortalsByPortalIDFormsEmployeeGetUnauthorized {
	return &PortalsByPortalIDFormsEmployeeGetUnauthorized{}
}

/*PortalsByPortalIDFormsEmployeeGetUnauthorized handles this case with default header values.

Unauthorized
*/
type PortalsByPortalIDFormsEmployeeGetUnauthorized struct {
}

func (o *PortalsByPortalIDFormsEmployeeGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /portals/{portal_id}/forms/employee][%d] portalsByPortalIdFormsEmployeeGetUnauthorized ", 401)
}

func (o *PortalsByPortalIDFormsEmployeeGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
