// Code generated by go-swagger; DO NOT EDIT.

package employees_gdpr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDResetGdprPasswordPutReader is a Reader for the EmployeesByIDResetGdprPasswordPut structure.
type EmployeesByIDResetGdprPasswordPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDResetGdprPasswordPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDResetGdprPasswordPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDResetGdprPasswordPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDResetGdprPasswordPutOK creates a EmployeesByIDResetGdprPasswordPutOK with default headers values
func NewEmployeesByIDResetGdprPasswordPutOK() *EmployeesByIDResetGdprPasswordPutOK {
	return &EmployeesByIDResetGdprPasswordPutOK{}
}

/*EmployeesByIDResetGdprPasswordPutOK handles this case with default header values.

Success
*/
type EmployeesByIDResetGdprPasswordPutOK struct {
	Payload bool
}

func (o *EmployeesByIDResetGdprPasswordPutOK) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/reset_gdpr_password][%d] employeesByIdResetGdprPasswordPutOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDResetGdprPasswordPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDResetGdprPasswordPutUnauthorized creates a EmployeesByIDResetGdprPasswordPutUnauthorized with default headers values
func NewEmployeesByIDResetGdprPasswordPutUnauthorized() *EmployeesByIDResetGdprPasswordPutUnauthorized {
	return &EmployeesByIDResetGdprPasswordPutUnauthorized{}
}

/*EmployeesByIDResetGdprPasswordPutUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDResetGdprPasswordPutUnauthorized struct {
}

func (o *EmployeesByIDResetGdprPasswordPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /employees/{id}/reset_gdpr_password][%d] employeesByIdResetGdprPasswordPutUnauthorized ", 401)
}

func (o *EmployeesByIDResetGdprPasswordPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
