// Code generated by go-swagger; DO NOT EDIT.

package employees_skills

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesSkillsGetParams creates a new EmployeesSkillsGetParams object
// with the default values initialized.
func NewEmployeesSkillsGetParams() *EmployeesSkillsGetParams {

	return &EmployeesSkillsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesSkillsGetParamsWithTimeout creates a new EmployeesSkillsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesSkillsGetParamsWithTimeout(timeout time.Duration) *EmployeesSkillsGetParams {

	return &EmployeesSkillsGetParams{

		timeout: timeout,
	}
}

// NewEmployeesSkillsGetParamsWithContext creates a new EmployeesSkillsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesSkillsGetParamsWithContext(ctx context.Context) *EmployeesSkillsGetParams {

	return &EmployeesSkillsGetParams{

		Context: ctx,
	}
}

// NewEmployeesSkillsGetParamsWithHTTPClient creates a new EmployeesSkillsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesSkillsGetParamsWithHTTPClient(client *http.Client) *EmployeesSkillsGetParams {

	return &EmployeesSkillsGetParams{
		HTTPClient: client,
	}
}

/*EmployeesSkillsGetParams contains all the parameters to send to the API endpoint
for the employees skills get operation typically these are written to a http.Request
*/
type EmployeesSkillsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees skills get params
func (o *EmployeesSkillsGetParams) WithTimeout(timeout time.Duration) *EmployeesSkillsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees skills get params
func (o *EmployeesSkillsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees skills get params
func (o *EmployeesSkillsGetParams) WithContext(ctx context.Context) *EmployeesSkillsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees skills get params
func (o *EmployeesSkillsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees skills get params
func (o *EmployeesSkillsGetParams) WithHTTPClient(client *http.Client) *EmployeesSkillsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees skills get params
func (o *EmployeesSkillsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesSkillsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
