// Code generated by go-swagger; DO NOT EDIT.

package employee_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/planday/models"
)

// EmployeesEmployeeTypesGetReader is a Reader for the EmployeesEmployeeTypesGet structure.
type EmployeesEmployeeTypesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesEmployeeTypesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesEmployeeTypesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesEmployeeTypesGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesEmployeeTypesGetOK creates a EmployeesEmployeeTypesGetOK with default headers values
func NewEmployeesEmployeeTypesGetOK() *EmployeesEmployeeTypesGetOK {
	return &EmployeesEmployeeTypesGetOK{}
}

/*EmployeesEmployeeTypesGetOK handles this case with default header values.

Success
*/
type EmployeesEmployeeTypesGetOK struct {
	Payload []*models.EmployeeTypeViewModel
}

func (o *EmployeesEmployeeTypesGetOK) Error() string {
	return fmt.Sprintf("[GET /employees/employee_types][%d] employeesEmployeeTypesGetOK  %+v", 200, o.Payload)
}

func (o *EmployeesEmployeeTypesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesEmployeeTypesGetUnauthorized creates a EmployeesEmployeeTypesGetUnauthorized with default headers values
func NewEmployeesEmployeeTypesGetUnauthorized() *EmployeesEmployeeTypesGetUnauthorized {
	return &EmployeesEmployeeTypesGetUnauthorized{}
}

/*EmployeesEmployeeTypesGetUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesEmployeeTypesGetUnauthorized struct {
}

func (o *EmployeesEmployeeTypesGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employees/employee_types][%d] employeesEmployeeTypesGetUnauthorized ", 401)
}

func (o *EmployeesEmployeeTypesGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
