// Code generated by go-swagger; DO NOT EDIT.

package custom_property_attachment_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetReader is a Reader for the EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGet structure.
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK creates a EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK with default headers values
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK {
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK{}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK handles this case with default header values.

Success
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK struct {
	Payload string
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK) Error() string {
	return fmt.Sprintf("[GET /employees/{id}/custom_properties/{custom_property_name}/attachment][%d] employeesByIdCustomPropertiesByCustomPropertyNameAttachmentGetOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized creates a EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized with default headers values
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized {
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized{}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized struct {
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employees/{id}/custom_properties/{custom_property_name}/attachment][%d] employeesByIdCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized ", 401)
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
