// Code generated by go-swagger; DO NOT EDIT.

package custom_property_attachment_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostReader is a Reader for the EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPost structure.
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK creates a EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK with default headers values
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK {
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK{}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK handles this case with default header values.

Success
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK struct {
	Payload string
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK) Error() string {
	return fmt.Sprintf("[POST /employees/{id}/custom_properties/{custom_property_name}/attachment][%d] employeesByIdCustomPropertiesByCustomPropertyNameAttachmentPostOK  %+v", 200, o.Payload)
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized creates a EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized with default headers values
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized {
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized{}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized handles this case with default header values.

Unauthorized
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized struct {
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /employees/{id}/custom_properties/{custom_property_name}/attachment][%d] employeesByIdCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized ", 401)
}

func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
