// Code generated by go-swagger; DO NOT EDIT.

package custom_property_attachment_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams object
// with the default values initialized.
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithTimeout creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams{

		timeout: timeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithContext creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams{

		Context: ctx,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithHTTPClient creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParamsWithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams{
		HTTPClient: client,
	}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams contains all the parameters to send to the API endpoint
for the employees by Id custom properties by custom property name attachment delete operation typically these are written to a http.Request
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams struct {

	/*CustomPropertyName
	  The name of the custom property.

	*/
	CustomPropertyName string
	/*ID
	  The id of the employee whose attachment value should be deleted.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WithCustomPropertyName(customPropertyName string) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	o.SetCustomPropertyName(customPropertyName)
	return o
}

// SetCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) SetCustomPropertyName(customPropertyName string) {
	o.CustomPropertyName = customPropertyName
}

// WithID adds the id to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WithID(id int64) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employees by Id custom properties by custom property name attachment delete params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param custom_property_name
	if err := r.SetPathParam("custom_property_name", o.CustomPropertyName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
