// Code generated by go-swagger; DO NOT EDIT.

package custom_property_attachment_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams object
// with the default values initialized.
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithTimeout creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams{

		timeout: timeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithContext creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams{

		Context: ctx,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithHTTPClient creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParamsWithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams{
		HTTPClient: client,
	}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams contains all the parameters to send to the API endpoint
for the employees by Id custom properties by custom property name attachment post operation typically these are written to a http.Request
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams struct {

	/*CustomPropertyName
	  The name of the custom property.

	*/
	CustomPropertyName string
	/*DataURI
	  The attachment as a data URI encoded in Base64.

	*/
	DataURI string
	/*ID
	  The id of the employee whose attachment value should be retrieved.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithCustomPropertyName(customPropertyName string) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetCustomPropertyName(customPropertyName)
	return o
}

// SetCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetCustomPropertyName(customPropertyName string) {
	o.CustomPropertyName = customPropertyName
}

// WithDataURI adds the dataURI to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithDataURI(dataURI string) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetDataURI(dataURI)
	return o
}

// SetDataURI adds the dataUri to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetDataURI(dataURI string) {
	o.DataURI = dataURI
}

// WithID adds the id to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WithID(id int64) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employees by Id custom properties by custom property name attachment post params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param custom_property_name
	if err := r.SetPathParam("custom_property_name", o.CustomPropertyName); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.DataURI); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
