// Code generated by go-swagger; DO NOT EDIT.

package custom_property_attachment_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams object
// with the default values initialized.
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams() *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithTimeout creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams{

		timeout: timeout,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithContext creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams{

		Context: ctx,
	}
}

// NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithHTTPClient creates a new EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParamsWithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	var ()
	return &EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams{
		HTTPClient: client,
	}
}

/*EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams contains all the parameters to send to the API endpoint
for the employees by Id custom properties by custom property name attachment get operation typically these are written to a http.Request
*/
type EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams struct {

	/*CustomPropertyName
	  The name of the custom property.

	*/
	CustomPropertyName string
	/*ID
	  The id of the employee whose attachment value should be retrieved.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WithTimeout(timeout time.Duration) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WithContext(ctx context.Context) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WithHTTPClient(client *http.Client) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WithCustomPropertyName(customPropertyName string) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	o.SetCustomPropertyName(customPropertyName)
	return o
}

// SetCustomPropertyName adds the customPropertyName to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) SetCustomPropertyName(customPropertyName string) {
	o.CustomPropertyName = customPropertyName
}

// WithID adds the id to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WithID(id int64) *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employees by Id custom properties by custom property name attachment get params
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesByIDCustomPropertiesByCustomPropertyNameAttachmentGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param custom_property_name
	if err := r.SetPathParam("custom_property_name", o.CustomPropertyName); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
