// Code generated by go-swagger; DO NOT EDIT.

package portals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPortalsSettingsGetParams creates a new PortalsSettingsGetParams object
// with the default values initialized.
func NewPortalsSettingsGetParams() *PortalsSettingsGetParams {
	var ()
	return &PortalsSettingsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPortalsSettingsGetParamsWithTimeout creates a new PortalsSettingsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPortalsSettingsGetParamsWithTimeout(timeout time.Duration) *PortalsSettingsGetParams {
	var ()
	return &PortalsSettingsGetParams{

		timeout: timeout,
	}
}

// NewPortalsSettingsGetParamsWithContext creates a new PortalsSettingsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPortalsSettingsGetParamsWithContext(ctx context.Context) *PortalsSettingsGetParams {
	var ()
	return &PortalsSettingsGetParams{

		Context: ctx,
	}
}

// NewPortalsSettingsGetParamsWithHTTPClient creates a new PortalsSettingsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPortalsSettingsGetParamsWithHTTPClient(client *http.Client) *PortalsSettingsGetParams {
	var ()
	return &PortalsSettingsGetParams{
		HTTPClient: client,
	}
}

/*PortalsSettingsGetParams contains all the parameters to send to the API endpoint
for the portals settings get operation typically these are written to a http.Request
*/
type PortalsSettingsGetParams struct {

	/*Name*/
	Name []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the portals settings get params
func (o *PortalsSettingsGetParams) WithTimeout(timeout time.Duration) *PortalsSettingsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the portals settings get params
func (o *PortalsSettingsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the portals settings get params
func (o *PortalsSettingsGetParams) WithContext(ctx context.Context) *PortalsSettingsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the portals settings get params
func (o *PortalsSettingsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the portals settings get params
func (o *PortalsSettingsGetParams) WithHTTPClient(client *http.Client) *PortalsSettingsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the portals settings get params
func (o *PortalsSettingsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the portals settings get params
func (o *PortalsSettingsGetParams) WithName(name []string) *PortalsSettingsGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the portals settings get params
func (o *PortalsSettingsGetParams) SetName(name []string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PortalsSettingsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesName := o.Name

	joinedName := swag.JoinByFormat(valuesName, "multi")
	// query array param name
	if err := r.SetQueryParam("name", joinedName...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
