// Code generated by go-swagger; DO NOT EDIT.

package portals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new portals API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for portals API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PortalsPut updates a portal s payment status setting the type to 11 will set it zuora
*/
func (a *Client) PortalsPut(params *PortalsPutParams, authInfo runtime.ClientAuthInfoWriter) (*PortalsPutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPortalsPutParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PortalsPut",
		Method:             "PUT",
		PathPattern:        "/portals",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PortalsPutReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PortalsPutOK), nil

}

/*
PortalsSettingsGet gets values of portal settings identified by names
*/
func (a *Client) PortalsSettingsGet(params *PortalsSettingsGetParams, authInfo runtime.ClientAuthInfoWriter) (*PortalsSettingsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPortalsSettingsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PortalsSettingsGet",
		Method:             "GET",
		PathPattern:        "/portals/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PortalsSettingsGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PortalsSettingsGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
