// Code generated by go-swagger; DO NOT EDIT.

package employees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmployeesByIDGetParams creates a new EmployeesByIDGetParams object
// with the default values initialized.
func NewEmployeesByIDGetParams() *EmployeesByIDGetParams {
	var ()
	return &EmployeesByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmployeesByIDGetParamsWithTimeout creates a new EmployeesByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmployeesByIDGetParamsWithTimeout(timeout time.Duration) *EmployeesByIDGetParams {
	var ()
	return &EmployeesByIDGetParams{

		timeout: timeout,
	}
}

// NewEmployeesByIDGetParamsWithContext creates a new EmployeesByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmployeesByIDGetParamsWithContext(ctx context.Context) *EmployeesByIDGetParams {
	var ()
	return &EmployeesByIDGetParams{

		Context: ctx,
	}
}

// NewEmployeesByIDGetParamsWithHTTPClient creates a new EmployeesByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmployeesByIDGetParamsWithHTTPClient(client *http.Client) *EmployeesByIDGetParams {
	var ()
	return &EmployeesByIDGetParams{
		HTTPClient: client,
	}
}

/*EmployeesByIDGetParams contains all the parameters to send to the API endpoint
for the employees by Id get operation typically these are written to a http.Request
*/
type EmployeesByIDGetParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the employees by Id get params
func (o *EmployeesByIDGetParams) WithTimeout(timeout time.Duration) *EmployeesByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the employees by Id get params
func (o *EmployeesByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the employees by Id get params
func (o *EmployeesByIDGetParams) WithContext(ctx context.Context) *EmployeesByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the employees by Id get params
func (o *EmployeesByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the employees by Id get params
func (o *EmployeesByIDGetParams) WithHTTPClient(client *http.Client) *EmployeesByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the employees by Id get params
func (o *EmployeesByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the employees by Id get params
func (o *EmployeesByIDGetParams) WithID(id int64) *EmployeesByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the employees by Id get params
func (o *EmployeesByIDGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EmployeesByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
