// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EmployeeListViewItemExtended employee list view item extended
// swagger:model EmployeeListViewItemExtended
type EmployeeListViewItemExtended struct {

	// item
	Item *EmployeeListViewItem `json:"item,omitempty"`

	// permissions
	Permissions []string `json:"permissions"`

	// property permission
	PropertyPermission []*PermissionViewModel `json:"property_permission"`
}

// Validate validates this employee list view item extended
func (m *EmployeeListViewItemExtended) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItem(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePropertyPermission(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EmployeeListViewItemExtended) validateItem(formats strfmt.Registry) error {

	if swag.IsZero(m.Item) { // not required
		return nil
	}

	if m.Item != nil {
		if err := m.Item.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("item")
			}
			return err
		}
	}

	return nil
}

func (m *EmployeeListViewItemExtended) validatePropertyPermission(formats strfmt.Registry) error {

	if swag.IsZero(m.PropertyPermission) { // not required
		return nil
	}

	for i := 0; i < len(m.PropertyPermission); i++ {
		if swag.IsZero(m.PropertyPermission[i]) { // not required
			continue
		}

		if m.PropertyPermission[i] != nil {
			if err := m.PropertyPermission[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("property_permission" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EmployeeListViewItemExtended) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmployeeListViewItemExtended) UnmarshalBinary(b []byte) error {
	var res EmployeeListViewItemExtended
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
