// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EmployeeGroupMembership employee group membership
// swagger:model EmployeeGroupMembership
type EmployeeGroupMembership struct {

	// created at
	// Read Only: true
	CreatedAt string `json:"created_at,omitempty"`

	// created by
	// Read Only: true
	CreatedBy int64 `json:"created_by,omitempty"`

	// date created
	// Read Only: true
	// Format: date-time
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// date deleted
	// Read Only: true
	// Format: date-time
	DateDeleted strfmt.DateTime `json:"date_deleted,omitempty"`

	// date modified
	// Read Only: true
	// Format: date-time
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// delete origin enum
	// Read Only: true
	DeleteOriginEnum int32 `json:"delete_origin_enum,omitempty"`

	// deleted at
	// Read Only: true
	DeletedAt string `json:"deleted_at,omitempty"`

	// deleted by
	// Read Only: true
	DeletedBy int64 `json:"deleted_by,omitempty"`

	// employee
	// Read Only: true
	Employee *Employee `json:"employee,omitempty"`

	// employee group
	// Read Only: true
	EmployeeGroup *EmployeeGroup `json:"employee_group,omitempty"`

	// employee group id
	// Read Only: true
	EmployeeGroupID int64 `json:"employee_group_id,omitempty"`

	// employee id
	// Read Only: true
	EmployeeID int64 `json:"employee_id,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// is deleted
	// Read Only: true
	IsDeleted *bool `json:"is_deleted,omitempty"`

	// last modified
	// Read Only: true
	LastModified string `json:"last_modified,omitempty"`

	// modified by
	// Read Only: true
	ModifiedBy int64 `json:"modified_by,omitempty"`

	// pay rates
	// Read Only: true
	// Unique: true
	PayRates []*PayRate `json:"pay_rates"`

	// raised events
	// Read Only: true
	RaisedEvents []*IdomainEvent `json:"raised_events"`

	// work hours
	// Read Only: true
	WorkHours float64 `json:"work_hours,omitempty"`

	// work hours based on
	// Read Only: true
	WorkHoursBasedOn int32 `json:"work_hours_based_on,omitempty"`
}

// Validate validates this employee group membership
func (m *EmployeeGroupMembership) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmployee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmployeeGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayRates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRaisedEvents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EmployeeGroupMembership) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(m.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("date_created", "body", "date-time", m.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *EmployeeGroupMembership) validateDateDeleted(formats strfmt.Registry) error {

	if swag.IsZero(m.DateDeleted) { // not required
		return nil
	}

	if err := validate.FormatOf("date_deleted", "body", "date-time", m.DateDeleted.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *EmployeeGroupMembership) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(m.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("date_modified", "body", "date-time", m.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *EmployeeGroupMembership) validateEmployee(formats strfmt.Registry) error {

	if swag.IsZero(m.Employee) { // not required
		return nil
	}

	if m.Employee != nil {
		if err := m.Employee.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("employee")
			}
			return err
		}
	}

	return nil
}

func (m *EmployeeGroupMembership) validateEmployeeGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.EmployeeGroup) { // not required
		return nil
	}

	if m.EmployeeGroup != nil {
		if err := m.EmployeeGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("employee_group")
			}
			return err
		}
	}

	return nil
}

func (m *EmployeeGroupMembership) validatePayRates(formats strfmt.Registry) error {

	if swag.IsZero(m.PayRates) { // not required
		return nil
	}

	if err := validate.UniqueItems("pay_rates", "body", m.PayRates); err != nil {
		return err
	}

	for i := 0; i < len(m.PayRates); i++ {
		if swag.IsZero(m.PayRates[i]) { // not required
			continue
		}

		if m.PayRates[i] != nil {
			if err := m.PayRates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pay_rates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EmployeeGroupMembership) validateRaisedEvents(formats strfmt.Registry) error {

	if swag.IsZero(m.RaisedEvents) { // not required
		return nil
	}

	for i := 0; i < len(m.RaisedEvents); i++ {
		if swag.IsZero(m.RaisedEvents[i]) { // not required
			continue
		}

		if m.RaisedEvents[i] != nil {
			if err := m.RaisedEvents[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("raised_events" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EmployeeGroupMembership) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmployeeGroupMembership) UnmarshalBinary(b []byte) error {
	var res EmployeeGroupMembership
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
