// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EmployeeViewModel employee view model
// swagger:model EmployeeViewModel
type EmployeeViewModel struct {

	// bank account
	BankAccount string `json:"bank_account,omitempty"`

	// bank reg number
	BankRegNumber string `json:"bank_reg_number,omitempty"`

	// birth date
	BirthDate string `json:"birth_date,omitempty"`

	// birthday
	// Read Only: true
	// Format: date-time
	Birthday strfmt.DateTime `json:"birthday,omitempty"`

	// cell phone
	CellPhone string `json:"cell_phone,omitempty"`

	// cell phone country id
	CellPhoneCountryID int64 `json:"cell_phone_country_id,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// contract rules rule id
	ContractRulesRuleID int64 `json:"contract_rules_rule_id,omitempty"`

	// country id
	CountryID int64 `json:"country_id,omitempty"`

	// date created
	DateCreated string `json:"date_created,omitempty"`

	// date modified
	DateModified string `json:"date_modified,omitempty"`

	// deactivation date
	DeactivationDate string `json:"deactivation_date,omitempty"`

	// departments
	Departments []int64 `json:"departments"`

	// description
	Description string `json:"description,omitempty"`

	// dismissed date
	// Read Only: true
	// Format: date-time
	DismissedDate strfmt.DateTime `json:"dismissed_date,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// employee groups
	EmployeeGroups []int64 `json:"employee_groups"`

	// employee type id
	EmployeeTypeID int64 `json:"employee_type_id,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// gender
	// Enum: [Male Female]
	Gender string `json:"gender,omitempty"`

	// has avatar
	HasAvatar bool `json:"has_avatar,omitempty"`

	// has been online
	HasBeenOnline bool `json:"has_been_online,omitempty"`

	// hired date
	// Read Only: true
	// Format: date-time
	HiredDate strfmt.DateTime `json:"hired_date,omitempty"`

	// hired from
	HiredFrom string `json:"hired_from,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// initials
	Initials string `json:"initials,omitempty"`

	// is public
	IsPublic bool `json:"is_public,omitempty"`

	// job title
	JobTitle string `json:"job_title,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// max access priority
	MaxAccessPriority int64 `json:"max_access_priority,omitempty"`

	// name
	// Read Only: true
	Name string `json:"name,omitempty"`

	// nick name
	NickName string `json:"nick_name,omitempty"`

	// pay rate
	PayRate float64 `json:"pay_rate,omitempty"`

	// permissions
	Permissions []string `json:"permissions"`

	// phone
	Phone string `json:"phone,omitempty"`

	// phone country id
	PhoneCountryID int64 `json:"phone_country_id,omitempty"`

	// primary department id
	PrimaryDepartmentID int64 `json:"primary_department_id,omitempty"`

	// roles
	// Read Only: true
	Roles []int64 `json:"roles"`

	// salary identifier
	SalaryIdentifier string `json:"salary_identifier,omitempty"`

	// security groups
	SecurityGroups []int64 `json:"security_groups"`

	// skills
	Skills []int64 `json:"skills"`

	// ssn
	Ssn string `json:"ssn,omitempty"`

	// street1
	Street1 string `json:"street1,omitempty"`

	// street2
	Street2 string `json:"street2,omitempty"`

	// subdivision id
	SubdivisionID int64 `json:"subdivision_id,omitempty"`

	// time zone
	TimeZone string `json:"time_zone,omitempty"`

	// time zone id
	// Read Only: true
	TimeZoneID int32 `json:"time_zone_id,omitempty"`

	// user name
	UserName string `json:"user_name,omitempty"`

	// work hours
	WorkHours float64 `json:"work_hours,omitempty"`

	// zip
	Zip string `json:"zip,omitempty"`

	// employee view model
	EmployeeViewModel map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *EmployeeViewModel) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// bank account
		BankAccount string `json:"bank_account,omitempty"`

		// bank reg number
		BankRegNumber string `json:"bank_reg_number,omitempty"`

		// birth date
		BirthDate string `json:"birth_date,omitempty"`

		// birthday
		// Read Only: true
		// Format: date-time
		Birthday strfmt.DateTime `json:"birthday,omitempty"`

		// cell phone
		CellPhone string `json:"cell_phone,omitempty"`

		// cell phone country id
		CellPhoneCountryID int64 `json:"cell_phone_country_id,omitempty"`

		// city
		City string `json:"city,omitempty"`

		// contract rules rule id
		ContractRulesRuleID int64 `json:"contract_rules_rule_id,omitempty"`

		// country id
		CountryID int64 `json:"country_id,omitempty"`

		// date created
		DateCreated string `json:"date_created,omitempty"`

		// date modified
		DateModified string `json:"date_modified,omitempty"`

		// deactivation date
		DeactivationDate string `json:"deactivation_date,omitempty"`

		// departments
		Departments []int64 `json:"departments"`

		// description
		Description string `json:"description,omitempty"`

		// dismissed date
		// Read Only: true
		// Format: date-time
		DismissedDate strfmt.DateTime `json:"dismissed_date,omitempty"`

		// email
		Email string `json:"email,omitempty"`

		// employee groups
		EmployeeGroups []int64 `json:"employee_groups"`

		// employee type id
		EmployeeTypeID int64 `json:"employee_type_id,omitempty"`

		// first name
		FirstName string `json:"first_name,omitempty"`

		// gender
		// Enum: [Male Female]
		Gender string `json:"gender,omitempty"`

		// has avatar
		HasAvatar bool `json:"has_avatar,omitempty"`

		// has been online
		HasBeenOnline bool `json:"has_been_online,omitempty"`

		// hired date
		// Read Only: true
		// Format: date-time
		HiredDate strfmt.DateTime `json:"hired_date,omitempty"`

		// hired from
		HiredFrom string `json:"hired_from,omitempty"`

		// id
		ID int64 `json:"id,omitempty"`

		// initials
		Initials string `json:"initials,omitempty"`

		// is public
		IsPublic bool `json:"is_public,omitempty"`

		// job title
		JobTitle string `json:"job_title,omitempty"`

		// last name
		LastName string `json:"last_name,omitempty"`

		// max access priority
		MaxAccessPriority int64 `json:"max_access_priority,omitempty"`

		// name
		// Read Only: true
		Name string `json:"name,omitempty"`

		// nick name
		NickName string `json:"nick_name,omitempty"`

		// pay rate
		PayRate float64 `json:"pay_rate,omitempty"`

		// permissions
		Permissions []string `json:"permissions"`

		// phone
		Phone string `json:"phone,omitempty"`

		// phone country id
		PhoneCountryID int64 `json:"phone_country_id,omitempty"`

		// primary department id
		PrimaryDepartmentID int64 `json:"primary_department_id,omitempty"`

		// roles
		// Read Only: true
		Roles []int64 `json:"roles"`

		// salary identifier
		SalaryIdentifier string `json:"salary_identifier,omitempty"`

		// security groups
		SecurityGroups []int64 `json:"security_groups"`

		// skills
		Skills []int64 `json:"skills"`

		// ssn
		Ssn string `json:"ssn,omitempty"`

		// street1
		Street1 string `json:"street1,omitempty"`

		// street2
		Street2 string `json:"street2,omitempty"`

		// subdivision id
		SubdivisionID int64 `json:"subdivision_id,omitempty"`

		// time zone
		TimeZone string `json:"time_zone,omitempty"`

		// time zone id
		// Read Only: true
		TimeZoneID int32 `json:"time_zone_id,omitempty"`

		// user name
		UserName string `json:"user_name,omitempty"`

		// work hours
		WorkHours float64 `json:"work_hours,omitempty"`

		// zip
		Zip string `json:"zip,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv EmployeeViewModel

	rcv.BankAccount = stage1.BankAccount

	rcv.BankRegNumber = stage1.BankRegNumber

	rcv.BirthDate = stage1.BirthDate

	rcv.Birthday = stage1.Birthday

	rcv.CellPhone = stage1.CellPhone

	rcv.CellPhoneCountryID = stage1.CellPhoneCountryID

	rcv.City = stage1.City

	rcv.ContractRulesRuleID = stage1.ContractRulesRuleID

	rcv.CountryID = stage1.CountryID

	rcv.DateCreated = stage1.DateCreated

	rcv.DateModified = stage1.DateModified

	rcv.DeactivationDate = stage1.DeactivationDate

	rcv.Departments = stage1.Departments

	rcv.Description = stage1.Description

	rcv.DismissedDate = stage1.DismissedDate

	rcv.Email = stage1.Email

	rcv.EmployeeGroups = stage1.EmployeeGroups

	rcv.EmployeeTypeID = stage1.EmployeeTypeID

	rcv.FirstName = stage1.FirstName

	rcv.Gender = stage1.Gender

	rcv.HasAvatar = stage1.HasAvatar

	rcv.HasBeenOnline = stage1.HasBeenOnline

	rcv.HiredDate = stage1.HiredDate

	rcv.HiredFrom = stage1.HiredFrom

	rcv.ID = stage1.ID

	rcv.Initials = stage1.Initials

	rcv.IsPublic = stage1.IsPublic

	rcv.JobTitle = stage1.JobTitle

	rcv.LastName = stage1.LastName

	rcv.MaxAccessPriority = stage1.MaxAccessPriority

	rcv.Name = stage1.Name

	rcv.NickName = stage1.NickName

	rcv.PayRate = stage1.PayRate

	rcv.Permissions = stage1.Permissions

	rcv.Phone = stage1.Phone

	rcv.PhoneCountryID = stage1.PhoneCountryID

	rcv.PrimaryDepartmentID = stage1.PrimaryDepartmentID

	rcv.Roles = stage1.Roles

	rcv.SalaryIdentifier = stage1.SalaryIdentifier

	rcv.SecurityGroups = stage1.SecurityGroups

	rcv.Skills = stage1.Skills

	rcv.Ssn = stage1.Ssn

	rcv.Street1 = stage1.Street1

	rcv.Street2 = stage1.Street2

	rcv.SubdivisionID = stage1.SubdivisionID

	rcv.TimeZone = stage1.TimeZone

	rcv.TimeZoneID = stage1.TimeZoneID

	rcv.UserName = stage1.UserName

	rcv.WorkHours = stage1.WorkHours

	rcv.Zip = stage1.Zip

	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "bank_account")

	delete(stage2, "bank_reg_number")

	delete(stage2, "birth_date")

	delete(stage2, "birthday")

	delete(stage2, "cell_phone")

	delete(stage2, "cell_phone_country_id")

	delete(stage2, "city")

	delete(stage2, "contract_rules_rule_id")

	delete(stage2, "country_id")

	delete(stage2, "date_created")

	delete(stage2, "date_modified")

	delete(stage2, "deactivation_date")

	delete(stage2, "departments")

	delete(stage2, "description")

	delete(stage2, "dismissed_date")

	delete(stage2, "email")

	delete(stage2, "employee_groups")

	delete(stage2, "employee_type_id")

	delete(stage2, "first_name")

	delete(stage2, "gender")

	delete(stage2, "has_avatar")

	delete(stage2, "has_been_online")

	delete(stage2, "hired_date")

	delete(stage2, "hired_from")

	delete(stage2, "id")

	delete(stage2, "initials")

	delete(stage2, "is_public")

	delete(stage2, "job_title")

	delete(stage2, "last_name")

	delete(stage2, "max_access_priority")

	delete(stage2, "name")

	delete(stage2, "nick_name")

	delete(stage2, "pay_rate")

	delete(stage2, "permissions")

	delete(stage2, "phone")

	delete(stage2, "phone_country_id")

	delete(stage2, "primary_department_id")

	delete(stage2, "roles")

	delete(stage2, "salary_identifier")

	delete(stage2, "security_groups")

	delete(stage2, "skills")

	delete(stage2, "ssn")

	delete(stage2, "street1")

	delete(stage2, "street2")

	delete(stage2, "subdivision_id")

	delete(stage2, "time_zone")

	delete(stage2, "time_zone_id")

	delete(stage2, "user_name")

	delete(stage2, "work_hours")

	delete(stage2, "zip")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.EmployeeViewModel = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m EmployeeViewModel) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// bank account
		BankAccount string `json:"bank_account,omitempty"`

		// bank reg number
		BankRegNumber string `json:"bank_reg_number,omitempty"`

		// birth date
		BirthDate string `json:"birth_date,omitempty"`

		// birthday
		// Read Only: true
		// Format: date-time
		Birthday strfmt.DateTime `json:"birthday,omitempty"`

		// cell phone
		CellPhone string `json:"cell_phone,omitempty"`

		// cell phone country id
		CellPhoneCountryID int64 `json:"cell_phone_country_id,omitempty"`

		// city
		City string `json:"city,omitempty"`

		// contract rules rule id
		ContractRulesRuleID int64 `json:"contract_rules_rule_id,omitempty"`

		// country id
		CountryID int64 `json:"country_id,omitempty"`

		// date created
		DateCreated string `json:"date_created,omitempty"`

		// date modified
		DateModified string `json:"date_modified,omitempty"`

		// deactivation date
		DeactivationDate string `json:"deactivation_date,omitempty"`

		// departments
		Departments []int64 `json:"departments"`

		// description
		Description string `json:"description,omitempty"`

		// dismissed date
		// Read Only: true
		// Format: date-time
		DismissedDate strfmt.DateTime `json:"dismissed_date,omitempty"`

		// email
		Email string `json:"email,omitempty"`

		// employee groups
		EmployeeGroups []int64 `json:"employee_groups"`

		// employee type id
		EmployeeTypeID int64 `json:"employee_type_id,omitempty"`

		// first name
		FirstName string `json:"first_name,omitempty"`

		// gender
		// Enum: [Male Female]
		Gender string `json:"gender,omitempty"`

		// has avatar
		HasAvatar bool `json:"has_avatar,omitempty"`

		// has been online
		HasBeenOnline bool `json:"has_been_online,omitempty"`

		// hired date
		// Read Only: true
		// Format: date-time
		HiredDate strfmt.DateTime `json:"hired_date,omitempty"`

		// hired from
		HiredFrom string `json:"hired_from,omitempty"`

		// id
		ID int64 `json:"id,omitempty"`

		// initials
		Initials string `json:"initials,omitempty"`

		// is public
		IsPublic bool `json:"is_public,omitempty"`

		// job title
		JobTitle string `json:"job_title,omitempty"`

		// last name
		LastName string `json:"last_name,omitempty"`

		// max access priority
		MaxAccessPriority int64 `json:"max_access_priority,omitempty"`

		// name
		// Read Only: true
		Name string `json:"name,omitempty"`

		// nick name
		NickName string `json:"nick_name,omitempty"`

		// pay rate
		PayRate float64 `json:"pay_rate,omitempty"`

		// permissions
		Permissions []string `json:"permissions"`

		// phone
		Phone string `json:"phone,omitempty"`

		// phone country id
		PhoneCountryID int64 `json:"phone_country_id,omitempty"`

		// primary department id
		PrimaryDepartmentID int64 `json:"primary_department_id,omitempty"`

		// roles
		// Read Only: true
		Roles []int64 `json:"roles"`

		// salary identifier
		SalaryIdentifier string `json:"salary_identifier,omitempty"`

		// security groups
		SecurityGroups []int64 `json:"security_groups"`

		// skills
		Skills []int64 `json:"skills"`

		// ssn
		Ssn string `json:"ssn,omitempty"`

		// street1
		Street1 string `json:"street1,omitempty"`

		// street2
		Street2 string `json:"street2,omitempty"`

		// subdivision id
		SubdivisionID int64 `json:"subdivision_id,omitempty"`

		// time zone
		TimeZone string `json:"time_zone,omitempty"`

		// time zone id
		// Read Only: true
		TimeZoneID int32 `json:"time_zone_id,omitempty"`

		// user name
		UserName string `json:"user_name,omitempty"`

		// work hours
		WorkHours float64 `json:"work_hours,omitempty"`

		// zip
		Zip string `json:"zip,omitempty"`
	}

	stage1.BankAccount = m.BankAccount

	stage1.BankRegNumber = m.BankRegNumber

	stage1.BirthDate = m.BirthDate

	stage1.Birthday = m.Birthday

	stage1.CellPhone = m.CellPhone

	stage1.CellPhoneCountryID = m.CellPhoneCountryID

	stage1.City = m.City

	stage1.ContractRulesRuleID = m.ContractRulesRuleID

	stage1.CountryID = m.CountryID

	stage1.DateCreated = m.DateCreated

	stage1.DateModified = m.DateModified

	stage1.DeactivationDate = m.DeactivationDate

	stage1.Departments = m.Departments

	stage1.Description = m.Description

	stage1.DismissedDate = m.DismissedDate

	stage1.Email = m.Email

	stage1.EmployeeGroups = m.EmployeeGroups

	stage1.EmployeeTypeID = m.EmployeeTypeID

	stage1.FirstName = m.FirstName

	stage1.Gender = m.Gender

	stage1.HasAvatar = m.HasAvatar

	stage1.HasBeenOnline = m.HasBeenOnline

	stage1.HiredDate = m.HiredDate

	stage1.HiredFrom = m.HiredFrom

	stage1.ID = m.ID

	stage1.Initials = m.Initials

	stage1.IsPublic = m.IsPublic

	stage1.JobTitle = m.JobTitle

	stage1.LastName = m.LastName

	stage1.MaxAccessPriority = m.MaxAccessPriority

	stage1.Name = m.Name

	stage1.NickName = m.NickName

	stage1.PayRate = m.PayRate

	stage1.Permissions = m.Permissions

	stage1.Phone = m.Phone

	stage1.PhoneCountryID = m.PhoneCountryID

	stage1.PrimaryDepartmentID = m.PrimaryDepartmentID

	stage1.Roles = m.Roles

	stage1.SalaryIdentifier = m.SalaryIdentifier

	stage1.SecurityGroups = m.SecurityGroups

	stage1.Skills = m.Skills

	stage1.Ssn = m.Ssn

	stage1.Street1 = m.Street1

	stage1.Street2 = m.Street2

	stage1.SubdivisionID = m.SubdivisionID

	stage1.TimeZone = m.TimeZone

	stage1.TimeZoneID = m.TimeZoneID

	stage1.UserName = m.UserName

	stage1.WorkHours = m.WorkHours

	stage1.Zip = m.Zip

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.EmployeeViewModel) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.EmployeeViewModel)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this employee view model
func (m *EmployeeViewModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBirthday(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDismissedDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHiredDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EmployeeViewModel) validateBirthday(formats strfmt.Registry) error {

	if swag.IsZero(m.Birthday) { // not required
		return nil
	}

	if err := validate.FormatOf("birthday", "body", "date-time", m.Birthday.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *EmployeeViewModel) validateDismissedDate(formats strfmt.Registry) error {

	if swag.IsZero(m.DismissedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("dismissed_date", "body", "date-time", m.DismissedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

var employeeViewModelTypeGenderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Male","Female"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		employeeViewModelTypeGenderPropEnum = append(employeeViewModelTypeGenderPropEnum, v)
	}
}

const (

	// EmployeeViewModelGenderMale captures enum value "Male"
	EmployeeViewModelGenderMale string = "Male"

	// EmployeeViewModelGenderFemale captures enum value "Female"
	EmployeeViewModelGenderFemale string = "Female"
)

// prop value enum
func (m *EmployeeViewModel) validateGenderEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, employeeViewModelTypeGenderPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *EmployeeViewModel) validateGender(formats strfmt.Registry) error {

	if swag.IsZero(m.Gender) { // not required
		return nil
	}

	// value enum
	if err := m.validateGenderEnum("gender", "body", m.Gender); err != nil {
		return err
	}

	return nil
}

func (m *EmployeeViewModel) validateHiredDate(formats strfmt.Registry) error {

	if swag.IsZero(m.HiredDate) { // not required
		return nil
	}

	if err := validate.FormatOf("hired_date", "body", "date-time", m.HiredDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EmployeeViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmployeeViewModel) UnmarshalBinary(b []byte) error {
	var res EmployeeViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
