// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IdomainEvent idomain event
// swagger:model IDomainEvent
type IdomainEvent struct {

	// aggregate id
	// Read Only: true
	AggregateID int64 `json:"aggregate_id,omitempty"`

	// caused by user id
	// Read Only: true
	CausedByUserID int64 `json:"caused_by_user_id,omitempty"`

	// event version
	// Read Only: true
	EventVersion int32 `json:"event_version,omitempty"`

	// occurred at
	// Read Only: true
	OccurredAt string `json:"occurred_at,omitempty"`

	// portal id
	// Read Only: true
	PortalID int64 `json:"portal_id,omitempty"`

	// security context portal id
	// Read Only: true
	SecurityContextPortalID int64 `json:"security_context_portal_id,omitempty"`
}

// Validate validates this idomain event
func (m *IdomainEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdomainEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdomainEvent) UnmarshalBinary(b []byte) error {
	var res IdomainEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
