// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InviteViewModel invite view model
// swagger:model InviteViewModel
type InviteViewModel struct {

	// department id
	DepartmentID int64 `json:"department_id,omitempty"`

	// email
	Email bool `json:"email,omitempty"`

	// employee id
	EmployeeID int64 `json:"employee_id,omitempty"`

	// sms
	Sms bool `json:"sms,omitempty"`
}

// Validate validates this invite view model
func (m *InviteViewModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InviteViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InviteViewModel) UnmarshalBinary(b []byte) error {
	var res InviteViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
