// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ResetPasswordViewModel reset password view model
// swagger:model ResetPasswordViewModel
type ResetPasswordViewModel struct {

	// id
	ID int64 `json:"id,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// send mail
	SendMail bool `json:"send_mail,omitempty"`

	// send sms
	SendSms bool `json:"send_sms,omitempty"`
}

// Validate validates this reset password view model
func (m *ResetPasswordViewModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResetPasswordViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResetPasswordViewModel) UnmarshalBinary(b []byte) error {
	var res ResetPasswordViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
