// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SecurityGroupViewModel security group view model
// swagger:model SecurityGroupViewModel
type SecurityGroupViewModel struct {

	// access priority
	AccessPriority int32 `json:"access_priority,omitempty"`

	// employee count
	EmployeeCount int32 `json:"employee_count,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// portal id
	PortalID int64 `json:"portal_id,omitempty"`
}

// Validate validates this security group view model
func (m *SecurityGroupViewModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecurityGroupViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecurityGroupViewModel) UnmarshalBinary(b []byte) error {
	var res SecurityGroupViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
