// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserProfileSecurityViewModel user profile security view model
// swagger:model UserProfileSecurityViewModel
type UserProfileSecurityViewModel struct {

	// is super user
	IsSuperUser bool `json:"is_super_user,omitempty"`

	// max access priority
	MaxAccessPriority int32 `json:"max_access_priority,omitempty"`

	// security context portal id
	SecurityContextPortalID int64 `json:"security_context_portal_id,omitempty"`

	// unsigned contracts
	UnsignedContracts bool `json:"unsigned_contracts,omitempty"`
}

// Validate validates this user profile security view model
func (m *UserProfileSecurityViewModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserProfileSecurityViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserProfileSecurityViewModel) UnmarshalBinary(b []byte) error {
	var res UserProfileSecurityViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
